[package]
name = "fibver"
version = "1.1.1"
authors = ["Brian Hjøllund <brian@hjoellund.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.9"
lazy_static = "1.3.0"
